### ISSUE TITLE
[build:c819a2ba] Invited users are allowed to comment

### ISSUE THREAD

**Issue by sekchai2** [pacedotdev/community#34] opened 2020-06-30 15:09 UTC
Not sure if this is a feature or a bug.

After inviting users to an Org, they are allowed to comment inside a card.  However they are unable to create new cards until joining the org?

I suspect because they haven't joined the Org, their thumbnails pic are not visible after comment.

See link here.
https://pace.dev/app/ritta/c/testing-multiple-orgs/1

**Comment by dahernan** [comment] 2020-06-30 15:27
Hi Sek, we will have a look, i think you mean, with no Teams, because you can not access anything in the org, if you don't join it first

**Comment by matryer** [comment] 2020-07-02 13:31
@sekchai2 We cannot access your org - but I wonder if you could explain again the steps you took to reproduce this?

Things to note:

1. When you accept the invite, you join the org - that's how you can see things (you will get an error if you try to access an org that you haven't been invited to)
2. Beyond that, you can only join and leave teams. This is optional, and doesn't prevent you from commenting (since we want everybody from an org to be able to collaborate with individual teams, without joining them).

Does that make sense?

**Comment by matryer** [comment] 2020-07-09 09:32
Closing because I think this is expected behaviour.

**Closed as completed by matryer** 2020-07-09 09:32 UTC
